# Generated by Django 4.2.6 on 2023-10-09 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trainstation', '0003_remove_routestop_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routestop',
            options={'ordering': ['Platform']},
        ),
        migrations.RenameField(
            model_name='routestop',
            old_name='stop_order',
            new_name='Platform',
        ),
    ]
