# Generated by Django 4.2.6 on 2023-10-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainstation', '0005_remove_route_description_remove_route_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
