# Generated by Django 4.2.6 on 2023-10-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainstation', '0008_route_train'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestop',
            name='Departure',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='arrival',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
