# Generated by Django 4.2.6 on 2023-10-11 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trainstation', '0009_routestop_departure_routestop_arrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='start_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_station_routes', to='Trainstation.station'),
        ),
    ]
