# Generated by Django 4.2.6 on 2023-10-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainstation', '0010_route_start_station'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routestop',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='routestop',
            name='Distance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
