# Generated by Django 4.2.6 on 2023-10-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainstation', '0011_alter_routestop_options_routestop_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routestop',
            name='Platform',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
