# Generated by Django 4.2.6 on 2023-10-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainstation', '0012_alter_routestop_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestop',
            name='reached',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='Distance',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Distance (KM)'),
        ),
    ]
