# Generated by Django 4.2.6 on 2023-10-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainstation', '0013_routestop_reached_alter_routestop_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestop',
            name='reaching_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Time to reach (Min)'),
        ),
    ]
