# Generated by Django 4.2.6 on 2023-10-12 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trainstation', '0014_routestop_reaching_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routestop',
            name='reached',
        ),
        migrations.RemoveField(
            model_name='routestop',
            name='reaching_time',
        ),
    ]
