# Generated by Django 4.2.6 on 2023-10-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainstation', '0016_routestop_reaching_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routestop',
            name='reaching_time',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
