# Generated by Django 4.2.6 on 2023-10-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainstation', '0021_ticketbooking_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbooking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
