# Generated by Django 4.2.6 on 2023-10-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainstation', '0022_ticketbooking_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketbooking',
            name='num_tickets',
        ),
        migrations.AddField(
            model_name='ticketbooking',
            name='reservation_seat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
