# Generated by Django 4.2.6 on 2023-10-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainstation', '0023_remove_ticketbooking_num_tickets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='base_fair',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
