# Generated by Django 4.2.6 on 2023-10-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainstation', '0024_train_base_fair'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='additional_charge',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
