# Generated by Django 4.2.6 on 2023-10-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainstation', '0025_train_additional_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketbooking',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='ticketbooking',
            name='razor_pay_order_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ticketbooking',
            name='razor_pay_payment_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ticketbooking',
            name='razor_pay_payment_signature',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
