# Generated by Django 4.2.6 on 2023-10-19 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trainstation', '0026_remove_ticketbooking_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbooking',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Trainstation.route'),
        ),
    ]
