# Generated by Django 4.2.6 on 2023-10-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainstation', '0027_ticketbooking_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbooking',
            name='ticket_image',
            field=models.ImageField(blank=True, null=True, upload_to='tickets'),
        ),
    ]
