# Generated by Django 4.2.6 on 2023-10-22 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trainstation', '0028_ticketbooking_ticket_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutesArrived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Arrived', models.BooleanField(default=False)),
                ('Departed', models.BooleanField(default=False)),
                ('route_stops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trainstation.routestop')),
            ],
        ),
        migrations.CreateModel(
            name='Train_tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trainstation.route')),
                ('route_stops', models.ManyToManyField(through='Trainstation.RoutesArrived', to='Trainstation.routestop')),
            ],
        ),
        migrations.AddField(
            model_name='routesarrived',
            name='train_tracking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trainstation.train_tracking'),
        ),
    ]
