# Generated by Django 4.2.6 on 2023-10-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainstation', '0029_routesarrived_train_tracking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routestop',
            name='Platform',
        ),
        migrations.AddField(
            model_name='routesarrived',
            name='Platform',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
