# Generated by Django 4.2.6 on 2023-10-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainstation', '0030_remove_routestop_platform_routesarrived_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrivilage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilage', models.CharField(choices=[('army', 'army'), ('dabled', 'dabled'), ('none', 'none')], default='none', max_length=100)),
                ('approve', models.BooleanField(default=False)),
            ],
        ),
    ]
