# Generated by Django 4.2.6 on 2023-10-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainstation', '0032_userprivilage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbooking',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
